#API APP
API_APP_IMAGE_TYPE=eve
API_APP_IMAGE_VERSION=0.2.1
API_PORT=9013
API_APP_PORT=9013
API_AUTH_USERNAME=admin
API_AUTH_PASSWORD=someverylongpassword
#DB
API_DB_HOST=127.0.0.1
API_DB_IMAGE_TYPE=mongo
API_DB_IMAGE_VERSION=4.2.3-bionic
API_DB_USERNAME=administrator 
API_DB_PASSWORD=verylongpasswordsome
API_ROOT_DB_USERNAME=root
API_ROOT_DB_PASSWORD=isverylongpasswordsome
API_DB_NAME=db 
API_DB_PORT=27017 
# DB_UI 
API_UI_IMAGE_TYPE=mongo-express
API_UI_IMAGE_VERSION=0.54.0
API_UI_APP_PORT=80
API_UI_PORT=9888
API_UI_USERNAME=admin
API_UI_PASSWORD=tisishwereyoshouldpoutpassword
